name: challenge
channels:
  - conda-forge
dependencies:
  - python=3.10.15
  - numpy=2.1.3
  - pytorch=2.4.1=cpu_generic_py310h7b7c402_0
  - stable-baselines3=2.3.2
  - cloudpickle=3.1.0
  - gym=0.26.2
  - mujoco=3.2.4
  - mushroom-rl=1.10.1
  - pip:
    - absl-py==2.1.0
    - gymnasium==0.28.1
    - ray==2.38.0